{% raw -%}
# ---

# yaml inventory based on https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
#
# In this inventory we only define "behavioral inventory parameters"
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
#
# ROLE VARIABLES SHOULD BE DEFINED IN "inventory/host_vars/" OR "inventory/group_vars/"
#
# Useful debug commands:
#
# print hostvars for host "vagrant-vm":
# $> ansible -i inventory/ -m debug -a var="hostvars['vagrant-vm']" vagrant-vm
#
# print groups for host "vagrant-vm":
# $> ansible -i inventory/ -m debug -a var="hostvars['vagrant-vm']['group_names']" vagrant-vm


# all:
#   vars:
#     ansible_ssh_extra_args: '-F {{ playbook_dir }}/inventory/ssh.cfg'

# vagrant:
#   hosts:
#     default:
#       ansible_host: 192.168.111.222
#       ansible_user: vagrant
#       local_apply_role_disable_selinux: True


# login_nodes:
#   hosts:
#     login1:
#       ansible_host: 191.168.100.32
#       ansible_user: root
#       ansible_port: 2222
#       ansible_ssh_private_key_file: ~/.ssh/id_rsa
#     login2:
#   vars:
#     local_apply_role_iptables: True
#     local_apply_role_fail2ban: True


# compute_nodes:
#   hosts:
#     compute1:
#     compute2:
#   vars:
#     local_apply_role_gpfs: True


# compute_cluster:
#   children:
#     login_nodes:
#     compute_nodes:


# webservers:
#   hosts:
#     web01:
#     web02:
#   vars:
#     local_apply_role_dehydrated: True
#     local_apply_role_apache: True
{% endraw -%}
