---

# yaml inventory based on https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml
#
# in this inventory we only define behavioral inventory parameters or local variables "local_apply_role_XXX"
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#connecting-to-hosts-behavioral-inventory-parameters
#
# Useful debug cheatsheets:
#
# print groups for host login1:
# $> ansible -i hosts.yml -m debug -a var="hostvars['login1']['group_names']" login1
#login1 | SUCCESS => {
#    "hostvars['login1']['group_names']": [
#        "compute_cluster",
#        "login_nodes"
#    ]
#}

# print which roles will apply to host login1
# $> ansible -i hosts.yml -m debug -a var="hostvars['login1']" login1 |grep local_apply_role
# "local_apply_role_x2go": true,

login_nodes:
  hosts:
    login1:
      ansible_host: 191.168.100.32
      ansible_user: root
    login2:
  vars:
    local_apply_role_x2go: True

compute_nodes:
  hosts:
    compute1:
    compute2:
  vars:
    local_apply_role_gpfs: True

compute_cluster:
  children:
    login_nodes:
    compute_nodes:
