---

# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
      - id: autopep8

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
