---

- name: {{cookiecutter.playbook_name}}
  hosts: all
  gather_facts: true
  remote_user: {{cookiecutter.ansible_user}}
  become: true
{% raw %}
  tasks:

    - name: Import vault.yml if it exists. This requires a valid vault password
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/vault.yml"  # yamllint disable-line rule:indentation
          skip: true
      tags: always
      no_log: true
      delegate_to: localhost
      become: false

    - name: PRE | COMMON | Common setup for every machine
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/common/pre.yml"
      tags:
        - common
        - common_pre

    # We use a block here as workaround so tags are inherited in dynamic includes
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword
    - block:

        - name: PRE | HOST SPECIFIC | host {{ inventory_hostname }}
          ansible.builtin.include_tasks: "{{ item }}"
          with_first_found:
            - files:
              - "{{ playbook_dir }}/tasks/hosts/{{ inventory_hostname }}_pre.yml"  # yamllint disable-line rule:indentation
              skip: true
      tags:
        - pre
        - pre_host
        - host_specific


    #  CUSTOM TASKS BY GROUP. IMPORT BELOW THE REQUIRED TASKS BY GROUP. e.g.
    #
    # - name: Custom setup for machines in group webservers
    #   ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/groups/webservers.yml"
    #   when: "'webservers' in group_names"
    #   tags: webservers


    # We use a block here as workaround so tags are inherited in dynamic includes
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword
    - block:

        - name: POST | HOST SPECIFIC | host {{ inventory_hostname }}
          ansible.builtin.include_tasks: "{{ item }}"
          with_first_found:
            - files:
              - "{{ playbook_dir }}/tasks/hosts/{{ inventory_hostname }}_post.yml"  # yamllint disable-line rule:indentation
              skip: true
      tags:
        - post
        - post_host
        - host_specific

    - name: POST COMMON | Common setup for every machine
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/common/post.yml"
      tags:
        - common
        - common_post
{% endraw -%}
