---

- name: {{cookiecutter.playbook_name}}
  hosts: all
  gather_facts: true
  remote_user: {{cookiecutter.ansible_user}}
  become: true

{% raw %}
  tasks:

    - name: Import inventory/vault.yml if it exists. This requires a valid vault password
      include_vars:
        file: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/inventory/vault.yml"
          skip: true

    - name: PRE COMMON | Common setup for every machine
      import_tasks: "{{ playbook_dir }}/tasks/common/pre.yml"

    - name: PRE HOST CUSTOMIZATION | host {{ inventory_hostname }}
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/host_pre/{{ inventory_hostname }}_pre.yml"
          skip: true

    - name: Deploy roles to host. Roles are selected based on variables "local_apply_role_XXX"
      import_tasks: "{{ playbook_dir }}/tasks/custom_roles_by_host.yml"

    # - name: Custom setup for machines in group webservers
    #   import_tasks: tasks/group/group_webservers.yml
    #   when: "'webservers' in group_names"

    - name: POST HOST CUSTOMIZATION | host {{ inventory_hostname }}
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/host_post/{{ inventory_hostname }}_post.yml"
          skip: true

    - name: POST COMMON | Common setup for every machine
      import_tasks: "{{ playbook_dir }}/tasks/common/post.yml"

{% endraw %}
