---

- name: {{cookiecutter.playbook_name}}
  hosts: all
  gather_facts: true
  remote_user: {{cookiecutter.ansible_user}}
  become: true

{% raw %}
  tasks:

    - name: Import inventory/vault.yml if it exists. This requires a valid vault password
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/inventory/vault.yml"
          skip: true
      tags: always
      no_log: true

    - name: PRE | COMMON | Common setup for every machine
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/common/pre.yml"
      tags:
        - common
        - common_pre

    - name: PRE | HOST SPECIFIC | host {{ inventory_hostname }}
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/hosts/{{ inventory_hostname }}_pre.yml"
          skip: true
      tags:
        - pre
        - pre_host
        - host_specific

    # CUSTOM TASKS BY GROUP. ADD BELOW THE REQUIRED TASKS BY GROUP. e.g.
    # - name: Custom setup for machines in group webservers
    #   ansible.builtin.import_tasks: tasks/groups/webservers.yml
    #   when: "'webservers' in group_names"

    - name: POST | HOST SPECIFIC | host {{ inventory_hostname }}
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/hosts/{{ inventory_hostname }}_post.yml"
          skip: true
      tags:
        - post
        - post_host
        - host_specific

    - name: POST COMMON | Common setup for every machine
      ansible.builtin.import_tasks: "{{ playbook_dir }}/tasks/common/post.yml"
      tags:
        - common
        - common_post

{% endraw %}
