---

- name: {{cookiecutter.playbook_name}}
  hosts: all
  gather_facts: true
  remote_user: {{cookiecutter.ansible_user}}
  become: true

{% raw %}
  tasks:

    - name: Check if vault file exists in inventory/vault.yml
      delegate_to: localhost
      become: false
      stat:
        path: "{{ playbook_dir }}/inventory/vault.yml"
      register: _vault_file_info

    - name: Import inventory/vault.yml if it exists
      include_vars:
        file: "{{ playbook_dir }}/inventory/vault.yml"
      when: _vault_file_info.stat.exists

    - name: PRE COMMON | Common setup for every machine
      import_tasks: tasks/common/pre.yml

    - name: PRE HOST CUSTOMIZATION | host {{ inventory_hostname }}
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/host_pre/{{ inventory_hostname }}_pre.yml"
          skip: true

    - name: Deploy roles to host. Roles are selected based on variables "local_apply_role_XXX"
      import_tasks: tasks/custom_roles_by_host.yml

    # - name: Custom setup for machines in group webservers
    #   import_tasks: tasks/group/group_webservers.yml
    #   when: "'webservers' in group_names"

    - name: POST HOST CUSTOMIZATION | host {{ inventory_hostname }}
      include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "{{ playbook_dir }}/tasks/host_post/{{ inventory_hostname }}_post.yml"
          skip: true

    - name: POST COMMON | Common setup for every machine
      import_tasks: tasks/common/post.yml

{% endraw %}
