# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "vagrant-ubuntu2204"
  config.vm.define "ubuntu2204"
  config.vm.network "private_network", ip: "192.168.111.222"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu2204"
    vb.memory = "512"
  end

  # config.vm.provision "ansible" do |ansible|
  #   ansible.playbook = "site.yml"
  #   ansible.inventory_path = "inventory/"
  #   ansible.host_key_checking = false
  #   ansible.limit = "vagrant-vm"
  #   #ansible.limit = "all"
  #   #ansible.raw_arguments = ["--list-hosts"]
  #   #ansible.tags="xnat"
  #   #ansible.verbose = "-vvv"
  # end

end
