---
{% raw %}
- name: set hostname to "{{ inventory_hostname }}" as defined in inventory
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname].inventory_hostname }}"
  when: "ansible_user_id != 'vagrant'"  # skip in vagrant
  tags: hostname

- name: Configure the network
  block:

    - name: configure network interfaces for RedHat family
      ansible.builtin.import_role:
        name: MichaelRigart.interfaces
      when:
        - ansible_os_family == 'RedHat'
        - interfaces_ether_interfaces | length > 0

    - name: Configure network interfaces for Debian family
      ansible.builtin.import_role:
        name: mrlesmithjr.netplan
      when:
        - ansible_os_family == 'Debian'
        - netplan_configuration | length > 0

    - meta: flush_handlers

  tags: network

- name: Configure NTP time
  ansible.builtin.import_role:
    name: geerlingguy.ntp

- name: Add EPEL yum repo | RedHat
  ansible.builtin.package:
    name: epel-release
    state: installed
  when: ansible_os_family == 'RedHat'

- name: Install some basic packages defined in variable "local_common_packages_to_install"
  ansible.builtin.package:
    name: "{{ local_common_packages_to_install[ansible_os_family] }}"

- name: Mount local file systems
  ansible.builtin.import_role:
    name: aeriscloud.disk
  when: disk_additional_disks | length > 0

- name: Mount NFS shares
  ansible.builtin.import_role:
    name: ome.nfs_mount
  when: nfs_share_mounts | length > 0

- name: Create local accounts
  ansible.builtin.import_role:
    name: robertdebock.users
  when: users_user_list | length > 0

- name: Force all notified handlers to run after initial PRE COMMON tasks
  ansible.builtin.meta: flush_handlers

# vim: tabstop=2 shiftwidth=2
{% endraw %}
