---
{% raw %}
- name: set hostname to "{{ inventory_hostname }}" as defined in inventory
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname].inventory_hostname }}"
  when: "ansible_user != 'vagrant'"  # skip in vagrant
  tags: hostname

- name: Configure the network
  tags: network
  block:

    - name: Configure network interfaces for Debian family if network config is defined
      ansible.builtin.import_role:
        name: mrlesmithjr.netplan
      when:
        - ansible_os_family == 'Debian'
        - netplan_configuration | length > 0

    - name: Flush handlers so network config is applied
      meta: flush_handlers

- name: Configure NTP time
  ansible.builtin.import_role:
    name: geerlingguy.ntp
  tags: ntp

- name: Install some basic packages defined in variable "local_common_packages_to_install"
  ansible.builtin.package:
    name: "{{ local_common_packages_to_install[ansible_os_family] }}"

- name: Format and mount local disks if defined
  ansible.builtin.import_role:
    name: aeriscloud.disk
  when: disk_additional_disks | length > 0
  tags: local_mounts

- name: Mount NFS shares if defined
  ansible.builtin.import_role:
    name: ome.nfs_mount
  when: nfs_share_mounts | length > 0
  tags: nfs_mounts

- name: Create local accounts if defined
  ansible.builtin.import_role:
    name: robertdebock.users
  when:
    - users_user_list is defined
    - users_user_list | length > 0
  tags: users_accounts

- name: Configure sshd if sshd config is defined
  ansible.builtin.import_role:
    name: willshersystems.sshd
  when: sshd | length > 0
  tags: sshd

- name: Configure fail2ban if fail2ban config is defined
  ansible.builtin.import_role:
    name: robertdebock.fail2ban
  when: fail2ban_jail_configuration | length > 0
  tags: fail2ban

- name: Force all notified handlers to run after initial PRE COMMON tasks
  ansible.builtin.meta: flush_handlers

# vim: tabstop=2 shiftwidth=2
{% endraw -%}
