---

# ROLES IN THIS FILE WON'T BE EXECUTED BY DEFAULT.
# ALL THESE ROLES DEPEND ON A CONDITIONAL VAR NAMED "LOCAL_APPLY_ROLE_XXX"
# VARS "LOCAL_APPLY_ROLE_XXX" ARE DEFINED IN THE INVENTORY

- name: Disable SElinux
  import_role:
    name: pescobar.selinux_disable
  when:
    - local_apply_role_disable_selinux | default(false) | bool
    - ansible_os_family == 'RedHat'
  tags:
    - selinux

- name: Configure rsyslog
  import_role:
    name: robertdebock.rsyslog
  when: local_apply_role_rsyslog | default(false) | bool
  tags:
    - rsyslog

- name: Configure iptables firewall
  import_role:
    name: geerlingguy.firewall
  when: local_apply_role_iptables | default(false) | bool
  tags:
    - network
    - firewall
    - iptables

- name: configure postfix
  import_role:
    name: robertdebock.postfix
  when: local_apply_role_postfix | default(false) | bool
  tags:
    - postfix
    - mail

- name: Configure the sshd server
  import_role:
    name: willshersystems.sshd
  when: local_apply_role_sshd | default(false) | bool
  tags:
    - ssh_config
    - ssh

- name: Install and enable fail2ban
  import_role:
    name: robertdebock.fail2ban
  when: local_apply_role_fail2ban | default(false) | bool
  tags: fail2ban

- name: Configure PHP
  import_role:
    name: geerlingguy.php
  when: local_apply_role_php | default(false) | bool
  tags:
    - php

- name: Configure MySQL
  import_role:
    name: geerlingguy.mysql
  when: local_apply_role_mysql | default(false) | bool
  tags:
    - mysql

- name: Configure PostgreSQL
  import_role:
    name: geerlingguy.postgresql
  when: local_apply_role_postgreql | default(false) | bool
  tags:
    - postgresql

- name: Configure dehydrated letsencrypt client
  import_role:
    name: pescobar.dehydrated
  when: local_apply_role_dehydrated | default(false) | bool
  tags:
    - dehydrated

- name: Configure Apache
  import_role:
    name: wcm_io_devops.apache
  when: local_apply_role_apache | default(false) | bool
  tags:
    - apache

# vim: tabstop=2 shiftwidth=2
