---

# ROLES IN THIS FILE WON'T BE EXECUTED BY DEFAULT.
# ALL THEM DEPEND ON A CONDITIONAL DEFINED BY A "FLOW_VAR" NAMED "LOCAL_XXX"

- name: Disable SElinux
  import_role:
    name: pescobar.selinux_disable
  when:
    - local_disable_selinux | default(false) | bool
    - ansible_os_family == 'RedHat'
  tags:
    - selinux

- name: Configure iptables firewall
  import_role:
    name: geerlingguy.firewall
  when: local_iptables_firewall | default(false) | bool
  tags:
    - network
    - firewall
    - iptables

- name: configure postfix
  import_role:
    name: robertdebock.postfix
  when: local_postfix | default(false) | bool
  tags:
    - postfix
    - mail

- name: Configure the sshd server
  import_role:
    name: willshersystems.sshd
  when: local_sshd | default(false) | bool
  tags:
    - ssh_config
    - ssh

- name: Install and enable fail2ban
  import_role:
    name: robertdebock.fail2ban
  when: local_fail2ban | default(false) | bool
  tags: fail2ban

# vim: tabstop=2 shiftwidth=2
