---

# ROLES IN THIS FILE WON'T BE EXECUTED BY DEFAULT.
# ALL THEM DEPEND ON A CONDITIONAL DEFINED BY "FLOW_VAR" NAMED "LOCAL_XXX"

- name: Configure iptables firewall
  import_role:
    name: geerlingguy.firewall
  when: local_iptables_firewall
  tags:
    - network
    - firewall
    - iptables

- name: configure postfix
  import_role:
    name: robertdebock.postfix
  when: local_postfix
  tags:
    - postfix
    - mail

- name: Configure the sshd server
  import_role:
    name: willshersystems.sshd
  when: local_sshd
  tags:
    - ssh_config
    - ssh

- name: Install and enable fail2ban
  import_role:
    name: robertdebock.fail2ban
  when: local_fail2ban
  tags: fail2ban

# vim: tabstop=2 shiftwidth=2
